server {
    listen       80 default_server;
    listen       [::]:80 default_server;
    server_name  _;
    
    # Измените эту строку:
    root         /mephi-web;
    
    # Остальные настройки...
    location / {
    }
}